[tool.poetry]
name = "resident-schedule"
version = "0.2.0"
description = ""
authors = ["David E. Weirich <weirich.david@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.1.3"
pandas = "^1.4.3"
xlrd = "^2.0.1"
SQLAlchemy = "^1.4.39"
openpyxl = "^3.0.10"
pyxlsb = "^1.0.10"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pytest = "^7.1.2"
flake8 = "^5.0.3"
mypy = "^0.971"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
